// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/folsomintel/fuse/internal/entspike/ent/host"
)

// HostCreate is the builder for creating a Host entity.
type HostCreate struct {
	config
	mutation *HostMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *HostCreate) SetURL(v string) *HostCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_c *HostCreate) SetTokenEncrypted(v []byte) *HostCreate {
	_c.mutation.SetTokenEncrypted(v)
	return _c
}

// SetRegion sets the "region" field.
func (_c *HostCreate) SetRegion(v string) *HostCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *HostCreate) SetNillableRegion(v *string) *HostCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *HostCreate) SetState(v host.State) *HostCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *HostCreate) SetNillableState(v *host.State) *HostCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *HostCreate) SetTenantID(v string) *HostCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *HostCreate) SetNillableTenantID(v *string) *HostCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCpusTotal sets the "cpus_total" field.
func (_c *HostCreate) SetCpusTotal(v int) *HostCreate {
	_c.mutation.SetCpusTotal(v)
	return _c
}

// SetNillableCpusTotal sets the "cpus_total" field if the given value is not nil.
func (_c *HostCreate) SetNillableCpusTotal(v *int) *HostCreate {
	if v != nil {
		_c.SetCpusTotal(*v)
	}
	return _c
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (_c *HostCreate) SetRAMMBTotal(v int) *HostCreate {
	_c.mutation.SetRAMMBTotal(v)
	return _c
}

// SetNillableRAMMBTotal sets the "ram_mb_total" field if the given value is not nil.
func (_c *HostCreate) SetNillableRAMMBTotal(v *int) *HostCreate {
	if v != nil {
		_c.SetRAMMBTotal(*v)
	}
	return _c
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (_c *HostCreate) SetStorageGBTotal(v int) *HostCreate {
	_c.mutation.SetStorageGBTotal(v)
	return _c
}

// SetNillableStorageGBTotal sets the "storage_gb_total" field if the given value is not nil.
func (_c *HostCreate) SetNillableStorageGBTotal(v *int) *HostCreate {
	if v != nil {
		_c.SetStorageGBTotal(*v)
	}
	return _c
}

// SetVMCountMax sets the "vm_count_max" field.
func (_c *HostCreate) SetVMCountMax(v int) *HostCreate {
	_c.mutation.SetVMCountMax(v)
	return _c
}

// SetNillableVMCountMax sets the "vm_count_max" field if the given value is not nil.
func (_c *HostCreate) SetNillableVMCountMax(v *int) *HostCreate {
	if v != nil {
		_c.SetVMCountMax(*v)
	}
	return _c
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (_c *HostCreate) SetCpusAllocated(v int) *HostCreate {
	_c.mutation.SetCpusAllocated(v)
	return _c
}

// SetNillableCpusAllocated sets the "cpus_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableCpusAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetCpusAllocated(*v)
	}
	return _c
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (_c *HostCreate) SetRAMMBAllocated(v int) *HostCreate {
	_c.mutation.SetRAMMBAllocated(v)
	return _c
}

// SetNillableRAMMBAllocated sets the "ram_mb_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableRAMMBAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetRAMMBAllocated(*v)
	}
	return _c
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (_c *HostCreate) SetStorageGBAllocated(v int) *HostCreate {
	_c.mutation.SetStorageGBAllocated(v)
	return _c
}

// SetNillableStorageGBAllocated sets the "storage_gb_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableStorageGBAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetStorageGBAllocated(*v)
	}
	return _c
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (_c *HostCreate) SetVMCountAllocated(v int) *HostCreate {
	_c.mutation.SetVMCountAllocated(v)
	return _c
}

// SetNillableVMCountAllocated sets the "vm_count_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableVMCountAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetVMCountAllocated(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *HostCreate) SetLabels(v map[string]string) *HostCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetArch sets the "arch" field.
func (_c *HostCreate) SetArch(v string) *HostCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_c *HostCreate) SetNillableArch(v *string) *HostCreate {
	if v != nil {
		_c.SetArch(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *HostCreate) SetLastSeenAt(v time.Time) *HostCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HostCreate) SetCreatedAt(v time.Time) *HostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HostCreate) SetNillableCreatedAt(v *time.Time) *HostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HostCreate) SetUpdatedAt(v time.Time) *HostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HostCreate) SetNillableUpdatedAt(v *time.Time) *HostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HostCreate) SetID(v string) *HostCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the HostMutation object of the builder.
func (_c *HostCreate) Mutation() *HostMutation {
	return _c.mutation
}

// Save creates the Host in the database.
func (_c *HostCreate) Save(ctx context.Context) (*Host, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HostCreate) SaveX(ctx context.Context) *Host {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HostCreate) defaults() {
	if _, ok := _c.mutation.Region(); !ok {
		v := host.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := host.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := host.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CpusTotal(); !ok {
		v := host.DefaultCpusTotal
		_c.mutation.SetCpusTotal(v)
	}
	if _, ok := _c.mutation.RAMMBTotal(); !ok {
		v := host.DefaultRAMMBTotal
		_c.mutation.SetRAMMBTotal(v)
	}
	if _, ok := _c.mutation.StorageGBTotal(); !ok {
		v := host.DefaultStorageGBTotal
		_c.mutation.SetStorageGBTotal(v)
	}
	if _, ok := _c.mutation.VMCountMax(); !ok {
		v := host.DefaultVMCountMax
		_c.mutation.SetVMCountMax(v)
	}
	if _, ok := _c.mutation.CpusAllocated(); !ok {
		v := host.DefaultCpusAllocated
		_c.mutation.SetCpusAllocated(v)
	}
	if _, ok := _c.mutation.RAMMBAllocated(); !ok {
		v := host.DefaultRAMMBAllocated
		_c.mutation.SetRAMMBAllocated(v)
	}
	if _, ok := _c.mutation.StorageGBAllocated(); !ok {
		v := host.DefaultStorageGBAllocated
		_c.mutation.SetStorageGBAllocated(v)
	}
	if _, ok := _c.mutation.VMCountAllocated(); !ok {
		v := host.DefaultVMCountAllocated
		_c.mutation.SetVMCountAllocated(v)
	}
	if _, ok := _c.mutation.Labels(); !ok {
		v := host.DefaultLabels
		_c.mutation.SetLabels(v)
	}
	if _, ok := _c.mutation.Arch(); !ok {
		v := host.DefaultArch
		_c.mutation.SetArch(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := host.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := host.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HostCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Host.url"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Host.region"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Host.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := host.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Host.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Host.tenant_id"`)}
	}
	if _, ok := _c.mutation.CpusTotal(); !ok {
		return &ValidationError{Name: "cpus_total", err: errors.New(`ent: missing required field "Host.cpus_total"`)}
	}
	if _, ok := _c.mutation.RAMMBTotal(); !ok {
		return &ValidationError{Name: "ram_mb_total", err: errors.New(`ent: missing required field "Host.ram_mb_total"`)}
	}
	if _, ok := _c.mutation.StorageGBTotal(); !ok {
		return &ValidationError{Name: "storage_gb_total", err: errors.New(`ent: missing required field "Host.storage_gb_total"`)}
	}
	if _, ok := _c.mutation.VMCountMax(); !ok {
		return &ValidationError{Name: "vm_count_max", err: errors.New(`ent: missing required field "Host.vm_count_max"`)}
	}
	if _, ok := _c.mutation.CpusAllocated(); !ok {
		return &ValidationError{Name: "cpus_allocated", err: errors.New(`ent: missing required field "Host.cpus_allocated"`)}
	}
	if _, ok := _c.mutation.RAMMBAllocated(); !ok {
		return &ValidationError{Name: "ram_mb_allocated", err: errors.New(`ent: missing required field "Host.ram_mb_allocated"`)}
	}
	if _, ok := _c.mutation.StorageGBAllocated(); !ok {
		return &ValidationError{Name: "storage_gb_allocated", err: errors.New(`ent: missing required field "Host.storage_gb_allocated"`)}
	}
	if _, ok := _c.mutation.VMCountAllocated(); !ok {
		return &ValidationError{Name: "vm_count_allocated", err: errors.New(`ent: missing required field "Host.vm_count_allocated"`)}
	}
	if _, ok := _c.mutation.Labels(); !ok {
		return &ValidationError{Name: "labels", err: errors.New(`ent: missing required field "Host.labels"`)}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "Host.arch"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Host.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Host.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Host.updated_at"`)}
	}
	return nil
}

func (_c *HostCreate) sqlSave(ctx context.Context) (*Host, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Host.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HostCreate) createSpec() (*Host, *sqlgraph.CreateSpec) {
	var (
		_node = &Host{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(host.Table, sqlgraph.NewFieldSpec(host.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(host.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.TokenEncrypted(); ok {
		_spec.SetField(host.FieldTokenEncrypted, field.TypeBytes, value)
		_node.TokenEncrypted = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(host.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(host.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(host.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CpusTotal(); ok {
		_spec.SetField(host.FieldCpusTotal, field.TypeInt, value)
		_node.CpusTotal = value
	}
	if value, ok := _c.mutation.RAMMBTotal(); ok {
		_spec.SetField(host.FieldRAMMBTotal, field.TypeInt, value)
		_node.RAMMBTotal = value
	}
	if value, ok := _c.mutation.StorageGBTotal(); ok {
		_spec.SetField(host.FieldStorageGBTotal, field.TypeInt, value)
		_node.StorageGBTotal = value
	}
	if value, ok := _c.mutation.VMCountMax(); ok {
		_spec.SetField(host.FieldVMCountMax, field.TypeInt, value)
		_node.VMCountMax = value
	}
	if value, ok := _c.mutation.CpusAllocated(); ok {
		_spec.SetField(host.FieldCpusAllocated, field.TypeInt, value)
		_node.CpusAllocated = value
	}
	if value, ok := _c.mutation.RAMMBAllocated(); ok {
		_spec.SetField(host.FieldRAMMBAllocated, field.TypeInt, value)
		_node.RAMMBAllocated = value
	}
	if value, ok := _c.mutation.StorageGBAllocated(); ok {
		_spec.SetField(host.FieldStorageGBAllocated, field.TypeInt, value)
		_node.StorageGBAllocated = value
	}
	if value, ok := _c.mutation.VMCountAllocated(); ok {
		_spec.SetField(host.FieldVMCountAllocated, field.TypeInt, value)
		_node.VMCountAllocated = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(host.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(host.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(host.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(host.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(host.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// HostCreateBulk is the builder for creating many Host entities in bulk.
type HostCreateBulk struct {
	config
	err      error
	builders []*HostCreate
}

// Save creates the Host entities in the database.
func (_c *HostCreateBulk) Save(ctx context.Context) ([]*Host, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Host, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HostCreateBulk) SaveX(ctx context.Context) []*Host {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
