// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/folsomintel/fuse/internal/entspike/ent/vm"
)

// VMCreate is the builder for creating a VM entity.
type VMCreate struct {
	config
	mutation *VMMutation
	hooks    []Hook
}

// SetHostID sets the "host_id" field.
func (_c *VMCreate) SetHostID(v string) *VMCreate {
	_c.mutation.SetHostID(v)
	return _c
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_c *VMCreate) SetNillableHostID(v *string) *VMCreate {
	if v != nil {
		_c.SetHostID(*v)
	}
	return _c
}

// SetNetworkHost sets the "network_host" field.
func (_c *VMCreate) SetNetworkHost(v string) *VMCreate {
	_c.mutation.SetNetworkHost(v)
	return _c
}

// SetNillableNetworkHost sets the "network_host" field if the given value is not nil.
func (_c *VMCreate) SetNillableNetworkHost(v *string) *VMCreate {
	if v != nil {
		_c.SetNetworkHost(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *VMCreate) SetState(v vm.State) *VMCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *VMCreate) SetURL(v string) *VMCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *VMCreate) SetNillableURL(v *string) *VMCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *VMCreate) SetTaskID(v string) *VMCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *VMCreate) SetNillableTaskID(v *string) *VMCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *VMCreate) SetTenantID(v string) *VMCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *VMCreate) SetNillableTenantID(v *string) *VMCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCpus sets the "cpus" field.
func (_c *VMCreate) SetCpus(v int) *VMCreate {
	_c.mutation.SetCpus(v)
	return _c
}

// SetNillableCpus sets the "cpus" field if the given value is not nil.
func (_c *VMCreate) SetNillableCpus(v *int) *VMCreate {
	if v != nil {
		_c.SetCpus(*v)
	}
	return _c
}

// SetRAMMB sets the "ram_mb" field.
func (_c *VMCreate) SetRAMMB(v int) *VMCreate {
	_c.mutation.SetRAMMB(v)
	return _c
}

// SetNillableRAMMB sets the "ram_mb" field if the given value is not nil.
func (_c *VMCreate) SetNillableRAMMB(v *int) *VMCreate {
	if v != nil {
		_c.SetRAMMB(*v)
	}
	return _c
}

// SetStorageGB sets the "storage_gb" field.
func (_c *VMCreate) SetStorageGB(v int) *VMCreate {
	_c.mutation.SetStorageGB(v)
	return _c
}

// SetNillableStorageGB sets the "storage_gb" field if the given value is not nil.
func (_c *VMCreate) SetNillableStorageGB(v *int) *VMCreate {
	if v != nil {
		_c.SetStorageGB(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *VMCreate) SetRegion(v string) *VMCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *VMCreate) SetNillableRegion(v *string) *VMCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetMaxRuntimeSeconds sets the "max_runtime_seconds" field.
func (_c *VMCreate) SetMaxRuntimeSeconds(v int) *VMCreate {
	_c.mutation.SetMaxRuntimeSeconds(v)
	return _c
}

// SetNillableMaxRuntimeSeconds sets the "max_runtime_seconds" field if the given value is not nil.
func (_c *VMCreate) SetNillableMaxRuntimeSeconds(v *int) *VMCreate {
	if v != nil {
		_c.SetMaxRuntimeSeconds(*v)
	}
	return _c
}

// SetIdleTimeoutSeconds sets the "idle_timeout_seconds" field.
func (_c *VMCreate) SetIdleTimeoutSeconds(v int) *VMCreate {
	_c.mutation.SetIdleTimeoutSeconds(v)
	return _c
}

// SetNillableIdleTimeoutSeconds sets the "idle_timeout_seconds" field if the given value is not nil.
func (_c *VMCreate) SetNillableIdleTimeoutSeconds(v *int) *VMCreate {
	if v != nil {
		_c.SetIdleTimeoutSeconds(*v)
	}
	return _c
}

// SetAuthTokenEncrypted sets the "auth_token_encrypted" field.
func (_c *VMCreate) SetAuthTokenEncrypted(v []byte) *VMCreate {
	_c.mutation.SetAuthTokenEncrypted(v)
	return _c
}

// SetSecretsEncrypted sets the "secrets_encrypted" field.
func (_c *VMCreate) SetSecretsEncrypted(v []byte) *VMCreate {
	_c.mutation.SetSecretsEncrypted(v)
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *VMCreate) SetLastError(v string) *VMCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *VMCreate) SetNillableLastError(v *string) *VMCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VMCreate) SetCreatedAt(v time.Time) *VMCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VMCreate) SetNillableCreatedAt(v *time.Time) *VMCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VMCreate) SetUpdatedAt(v time.Time) *VMCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VMCreate) SetNillableUpdatedAt(v *time.Time) *VMCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VMCreate) SetID(v string) *VMCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the VMMutation object of the builder.
func (_c *VMCreate) Mutation() *VMMutation {
	return _c.mutation
}

// Save creates the VM in the database.
func (_c *VMCreate) Save(ctx context.Context) (*VM, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VMCreate) SaveX(ctx context.Context) *VM {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VMCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VMCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VMCreate) defaults() {
	if _, ok := _c.mutation.HostID(); !ok {
		v := vm.DefaultHostID
		_c.mutation.SetHostID(v)
	}
	if _, ok := _c.mutation.NetworkHost(); !ok {
		v := vm.DefaultNetworkHost
		_c.mutation.SetNetworkHost(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := vm.DefaultURL
		_c.mutation.SetURL(v)
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		v := vm.DefaultTaskID
		_c.mutation.SetTaskID(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := vm.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Cpus(); !ok {
		v := vm.DefaultCpus
		_c.mutation.SetCpus(v)
	}
	if _, ok := _c.mutation.RAMMB(); !ok {
		v := vm.DefaultRAMMB
		_c.mutation.SetRAMMB(v)
	}
	if _, ok := _c.mutation.StorageGB(); !ok {
		v := vm.DefaultStorageGB
		_c.mutation.SetStorageGB(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := vm.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.MaxRuntimeSeconds(); !ok {
		v := vm.DefaultMaxRuntimeSeconds
		_c.mutation.SetMaxRuntimeSeconds(v)
	}
	if _, ok := _c.mutation.IdleTimeoutSeconds(); !ok {
		v := vm.DefaultIdleTimeoutSeconds
		_c.mutation.SetIdleTimeoutSeconds(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := vm.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vm.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vm.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VMCreate) check() error {
	if _, ok := _c.mutation.HostID(); !ok {
		return &ValidationError{Name: "host_id", err: errors.New(`ent: missing required field "VM.host_id"`)}
	}
	if _, ok := _c.mutation.NetworkHost(); !ok {
		return &ValidationError{Name: "network_host", err: errors.New(`ent: missing required field "VM.network_host"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "VM.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := vm.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "VM.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "VM.url"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "VM.task_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "VM.tenant_id"`)}
	}
	if _, ok := _c.mutation.Cpus(); !ok {
		return &ValidationError{Name: "cpus", err: errors.New(`ent: missing required field "VM.cpus"`)}
	}
	if _, ok := _c.mutation.RAMMB(); !ok {
		return &ValidationError{Name: "ram_mb", err: errors.New(`ent: missing required field "VM.ram_mb"`)}
	}
	if _, ok := _c.mutation.StorageGB(); !ok {
		return &ValidationError{Name: "storage_gb", err: errors.New(`ent: missing required field "VM.storage_gb"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "VM.region"`)}
	}
	if _, ok := _c.mutation.MaxRuntimeSeconds(); !ok {
		return &ValidationError{Name: "max_runtime_seconds", err: errors.New(`ent: missing required field "VM.max_runtime_seconds"`)}
	}
	if _, ok := _c.mutation.IdleTimeoutSeconds(); !ok {
		return &ValidationError{Name: "idle_timeout_seconds", err: errors.New(`ent: missing required field "VM.idle_timeout_seconds"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "VM.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VM.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VM.updated_at"`)}
	}
	return nil
}

func (_c *VMCreate) sqlSave(ctx context.Context) (*VM, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected VM.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VMCreate) createSpec() (*VM, *sqlgraph.CreateSpec) {
	var (
		_node = &VM{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vm.Table, sqlgraph.NewFieldSpec(vm.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.HostID(); ok {
		_spec.SetField(vm.FieldHostID, field.TypeString, value)
		_node.HostID = value
	}
	if value, ok := _c.mutation.NetworkHost(); ok {
		_spec.SetField(vm.FieldNetworkHost, field.TypeString, value)
		_node.NetworkHost = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(vm.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(vm.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(vm.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(vm.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Cpus(); ok {
		_spec.SetField(vm.FieldCpus, field.TypeInt, value)
		_node.Cpus = value
	}
	if value, ok := _c.mutation.RAMMB(); ok {
		_spec.SetField(vm.FieldRAMMB, field.TypeInt, value)
		_node.RAMMB = value
	}
	if value, ok := _c.mutation.StorageGB(); ok {
		_spec.SetField(vm.FieldStorageGB, field.TypeInt, value)
		_node.StorageGB = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(vm.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.MaxRuntimeSeconds(); ok {
		_spec.SetField(vm.FieldMaxRuntimeSeconds, field.TypeInt, value)
		_node.MaxRuntimeSeconds = value
	}
	if value, ok := _c.mutation.IdleTimeoutSeconds(); ok {
		_spec.SetField(vm.FieldIdleTimeoutSeconds, field.TypeInt, value)
		_node.IdleTimeoutSeconds = value
	}
	if value, ok := _c.mutation.AuthTokenEncrypted(); ok {
		_spec.SetField(vm.FieldAuthTokenEncrypted, field.TypeBytes, value)
		_node.AuthTokenEncrypted = value
	}
	if value, ok := _c.mutation.SecretsEncrypted(); ok {
		_spec.SetField(vm.FieldSecretsEncrypted, field.TypeBytes, value)
		_node.SecretsEncrypted = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(vm.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vm.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vm.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// VMCreateBulk is the builder for creating many VM entities in bulk.
type VMCreateBulk struct {
	config
	err      error
	builders []*VMCreate
}

// Save creates the VM entities in the database.
func (_c *VMCreateBulk) Save(ctx context.Context) ([]*VM, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VM, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VMMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VMCreateBulk) SaveX(ctx context.Context) []*VM {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VMCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VMCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
